export default {
  FETCH_SCHEDULE: "FETCH_SCHEDULE",
  FETCH_SCHEDULE_SUCCESS: "FETCH_SCHEDULE_SUCCESS",
  FETCH_SCHEDULE_FAILED: "FETCH_SCHEDULE_FAILED",
  UPDATE_ASSIGNMENT_DATE: "UPDATE_ASSIGNMENT_DATE",
  UPDATE_ASSIGNMENT_DATE_SUCCESS: "UPDATE_ASSIGNMENT_DATE_SUCCESS",
  UPDATE_ASSIGNMENT_DATE_FAILED: "UPDATE_ASSIGNMENT_DATE_FAILED",
  SAVE_SCHEDULE: "SAVE_SCHEDULE",
  SAVE_SCHEDULE_SUCCESS: "SAVE_SCHEDULE_SUCCESS",
  LOAD_SCHEDULE_FROM_STORAGE: "LOAD_SCHEDULE_FROM_STORAGE",
};
